server:
  port: 8080
  contextPath: /rest-socket
  basePath: http://localhost
  error:
      path: /error
      whitelabel:
          enabled: false
  ssl:
    enabled: false
    key-store: classpath:main.jks
    key-password: secret
  socket:
    text:
        contextPath: /text
---
spring:
  profiles: local, default
  resources:
    #staticLocations: classpath:/static/
    #cachePeriod: 0
  application:
      name: REST API socket
      thymeleaf:
          cache: false
          enabled: true
          prefix: classpath:/templates/
          suffix: .html
          checkTemplateLocation: true
          mode: LEGACYHTML5
          encoding: UTF-8
          contentType: text/html
  main:
      banner-mode: "console"